USE [master]
GO
/****** Object:  Database [xound]    Script Date: 9/20/2016 4:48:03 PM ******/
CREATE DATABASE [xound]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'xound', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\xound.mdf' , SIZE = 1958912KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'xound_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\xound_log.ldf' , SIZE = 1008000KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [xound] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [xound].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [xound] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [xound] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [xound] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [xound] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [xound] SET ARITHABORT OFF 
GO
ALTER DATABASE [xound] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [xound] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [xound] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [xound] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [xound] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [xound] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [xound] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [xound] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [xound] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [xound] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [xound] SET  DISABLE_BROKER 
GO
ALTER DATABASE [xound] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [xound] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [xound] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [xound] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [xound] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [xound] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [xound] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [xound] SET RECOVERY FULL 
GO
ALTER DATABASE [xound] SET  MULTI_USER 
GO
ALTER DATABASE [xound] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [xound] SET DB_CHAINING OFF 
GO
ALTER DATABASE [xound] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [xound] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [xound]
GO
/****** Object:  Table [dbo].[Albums]    Script Date: 9/20/2016 4:48:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Albums](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](150) NOT NULL,
	[Year] [int] NOT NULL,
	[Genre] [nvarchar](50) NULL,
	[MainArtistID] [int] NULL,
	[ArtworkImageURL] [nvarchar](200) NULL,
	[ArtworkDominantColor] [nvarchar](10) NULL,
	[ArtworkContrastColor] [nvarchar](10) NULL,
	[TrackCount] [int] NULL,
	[Active] [bit] NOT NULL,
	[InsertDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Album] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TrackFiles]    Script Date: 9/20/2016 4:48:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TrackFiles](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TrackID] [int] NOT NULL,
	[Track] [varbinary](max) NOT NULL,
	[Active] [bit] NOT NULL,
	[InsertDate] [datetime] NOT NULL,
 CONSTRAINT [PK_TrackFiles] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Tracks]    Script Date: 9/20/2016 4:48:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tracks](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](150) NOT NULL,
	[TrackNo] [int] NOT NULL,
	[DurationMinutes] [int] NOT NULL,
	[DurationSeconds] [int] NOT NULL,
	[AlbumID] [int] NOT NULL,
	[Active] [bit] NOT NULL,
	[InsertDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Tracks] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [xound] SET  READ_WRITE 
GO
